---
# This playbook installs nginx as a Docker container on a remote host and mounts a volume

- hosts: gitprod
  become: yes
  tasks:

    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull
    - name: Create volume
      docker_volume:
        name: nginx-data
        driver: local
    - name: Run nginx Docker container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "nginx-data:/usr/share/nginx/html:ro"
    


