# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module
# https://hub.docker.com/_/sonarqube

- name: "installation SonarQube"
  hosts: sonar
  tasks:
    - name: changer config sysctl qui est requise pour ElasticSearch (donc SonarQube)
      sysctl: name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }
        - { key: "fs.file-max", value: "131072" }

    - name: creation dossier projet
      file:
        state: directory
        path: ~/sonar
    - name: Copier fichier docker-compose
      copy:
        src: ../files/docker-compose_sonar.yml
        dest: ~/sonar/docker-compose.yml

    - name: arret et supprimer les services existant déjà (optionelle?)
      docker_compose:
        project_src: ~/sonar
        state: absent

    - name: creation et démarrage du services par docker compose up
      docker_compose:
        project_src: ~/sonar
