---

- name: install gitea
  hosts: gitprod
  become: true
  become_user: root
  vars:
    docker_dir: /home/gitea/docker

  tasks:
  # TODO check is exist
  - name: Add google DNS server
    command: /bin/sh -c "echo \"nameserver 8.8.8.8\" >> /etc/resolv.conf"


  - name: Add the user 'gitea' with a specific uid and a primary group of 'gitea'
    user:
      name: gitea
      comment: Gitea user
      uid: 1040
      home: /home/gitea

  - name: Add user "git"
    user:
      name: git
      comment: Git user
      uid: 1041
      shell: /bin/sh
      home: /home/git

  - name: Create worck dir for docker-compose
    file:
      path: "{{docker_dir}}"
      recurse: true
      owner: gitea
      group: gitea
      state: directory

  - name: Copy docker compose file
    copy:
      src: ./../docker-compose-gitea.yml
      dest: "{{docker_dir}}"
      owner: gitea
      group: gitea


  - name: Start docker containers
    command: /bin/sh -c "cd {{docker_dir}} && docker-compose -f docker-compose-gitea.yml up -d"


 
