# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module
# https://hub.docker.com/_/sonarqube

- name: "installation Gitea"
  hosts: gitprod
  vars:
    docker_dir: ~/gitea/
  tasks:
    - name: creation dossier projet
      file:
        state: directory
        path: "{{docker_dir}}"
    - name: Copier fichier docker-compose
      copy:
        src: ../files/docker-compose_gitea.yml
        dest: "{{docker_dir}}/docker-compose.yml"


    - name: creation et démarrage du services par docker compose up
      docker_compose:
        project_src: "{{docker_dir}}"
